### PR TITLE
Add another print statement

### PR DESCRIPTION
**Pull request by tmeagher1501**
Add print statement test02

### CODE REVIEW

**Comment by tmeagher1500** [comment]
Your code looks good. Please add another print statement.

**Comment by tmeagher1501** [comment]
Add GitTest03

**Comment by tmeagher1500** [comment]
Code looks good. Please merge.

**Comment by tmeagher1501** [comment]
merge branch01 with master branch

**Comment by tmeagher1501** [comment]
After successful  branch01 merge with master comment.

**Pull request merged**
